Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2023-09, with the labels that each got.

#123 Feat/#116 대진표 컴포넌트 구성
  __mocks__/constants/matchRoundMock.ts
  __mocks__/handlers/bracketHandlers.ts
  src/@types/bracket.ts
  src/components/Bracket/BracketContents.tsx
  src/components/Bracket/BracketHeaders.tsx
  src/pages/contents/[channelLink]/bracket.tsx
Labels: ✨ Feat

#124 Refactor/#122: 모달창 전역으로 관리하도록 리팩토링
  __test__/components/Sidebar/ChannelBar/SelectChannelType.test.tsx
  src/@types/modals.ts
  src/components/Content/ContentModify.tsx
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Modal/ParticipantLists/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/showModals.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/layout.tsx
  src/components/providers/ModalProvider.tsx
  src/contexts/ModalContext.tsx
  src/hooks/useModals.ts
  src/pages/_app.tsx
Labels: ✨ Feat, 🧑‍🔧 Refactor

#121 Feat/#120: 관리자는 채널정보를 수정할 수 있는 모달 및 기능 추가
  __mocks__/handlers/channelHandlers.ts
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
Labels: ✨ Feat

#129 Feat/#125 채널 참가하기 기능 추가
  __mocks__/handlers/channelHandlers.ts
  __test__/components/Sidebar/ChannelBar/SelectChannelType.test.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
Labels: ✨ Feat

#130 Feat/#127 프로필 및 채널에 이미지 추가
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/@types/channelCircle.ts
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
  src/components/providers/ProfileProvider.tsx
Labels: ✨ Feat

#132 Feat/#131 채널 생성 시 이미지 업로드 구현
  next.config.js
  src/components/MakeChannel/SelectRule.tsx
  src/components/providers/MakeGameProvider.tsx
  src/constants/MakeGame.ts
  src/contexts/MakeGameContext.tsx
  src/pages/make-channel.tsx
Labels: ✨ Feat

#138 Feat/#137: 경기 참가요청할 수 있도록 추가했어요
  __mocks__/handlers/channelHandlers.ts
  src/components/Modal/JoinLeague/JoinLeague.tsx
Labels: ✨ Feat

#140 Feat/#139: 참여자 체크인 및 관리자 호출할 수 있는 페이지 추가
  __mocks__/browser.ts
  __mocks__/handlers/channelHandlers.ts
  __mocks__/handlers/matchHandlers.ts
  __mocks__/server.ts
  src/components/RoundCheckIn/CallAdminChat.tsx
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
  src/components/RoundCheckIn/index.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/pages/contents/[channelLink]/checkIn.tsx
  src/styles/GlobalStyle.tsx
Labels: ✨ Feat

#142 Config: socket 관련 라이브러리 설치
  package.json
  yarn.lock
Labels: ⚙️ Config

#134 Feat: 헤더 드롭다운 메뉴 추가
  src/components/Header/Header.tsx
Labels: ✨ Feat

#145 Feat/#144 라운드별 매치 횟수를 설정 및 대진표 기본 디자인
  __mocks__/constants/matchRoundMock.ts
  __mocks__/handlers/bracketHandlers.ts
  src/@types/channelConfig.ts
  src/@types/icon.ts
  src/components/Bracket/BracketContents.tsx
  src/components/Icon/index.tsx
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/ModifyChannel/BasicInfoChannel.tsx
  src/components/ModifyChannel/BracketInfoChannel.tsx
Labels: ✨ Feat

#146 Feat/#143: 준비 버튼에 소켓기능 추가
  __mocks__/handlers/matchHandlers.ts
  package.json
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
  src/components/RoundCheckIn/index.tsx
  src/config/index.ts
  src/config/stomp.ts
  src/pages/contents/[channelLink]/checkIn.tsx
  src/pages/contents/[channelLink]/checkIn/[matchId].tsx
  yarn.lock
Labels: ✨ Feat

#148 Feat/#147: 관리자는 공지사항 게시판 위치 변경할 수 있도록 추가
  __mocks__/handlers/boardHandlers.ts
  src/components/Sidebar/BoardBar/BoardBody.tsx
Labels: ✨ Feat

#151 Fix: 관리자가 참여자 권한 변경하는 요청 URI 변경
  src/components/Modal/ParticipantLists/RequestUser.tsx
Labels: 🛠 Fix
