Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2023-10, with the labels that each got.

#154 Fix: 서버 요청에 유저 인증 토큰값을 넣어 보내기 위해 axios -> authAPI 로 변경
  src/components/Modal/JoinLeague/JoinLeague.tsx
Labels: 🛠 Fix

#156 Feat/#149: 채팅기능 추가
  __mocks__/handlers/boardHandlers.ts
  __mocks__/handlers/matchHandlers.ts
  package.json
  src/components/RoundCheckIn/CallAdminChat.tsx
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
  src/components/RoundCheckIn/index.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/pages/contents/[channelLink]/checkIn/[matchId].tsx
Labels: ✨ Feat

#162 Fix: 배포시 에러 수정
  src/components/Sidebar/BoardBar/BoardBody.tsx
Labels: 🛠 Fix

#163 Fix: 채널 보드 조회 안되는 문제 수정
  src/components/Sidebar/BoardBar/BoardBody.tsx
Labels: 🛠 Fix

#159 Feat/#152 대회 개최 및 참여시 모달 형식으로 변경
  __test__/components/MakeChannel/SelectGame.test.tsx
  __test__/components/MakeChannel/SelectRule.test.tsx
  __test__/components/Sidebar/ChannelBar/SelectChannelType.test.tsx
  src/components/MakeChannel/SelectGame.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/components/providers/MakeGameProvider.tsx
  src/constants/MakeGame.ts
  src/contexts/MakeGameContext.tsx
  src/pages/make-channel.tsx
Labels: ✨ Feat

#164 Fix: 채널 보드 조회 안되는 문제 해결
  src/components/Sidebar/BoardBar/BoardBody.tsx
Labels: 🛠 Fix

#166 Feat/#160 관리자 페이지 추가 및 대진표 보드 추가
  __mocks__/browser.ts
  __mocks__/handlers/adminHandlers.ts
  __mocks__/server.ts
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/pages/contents/[channelLink]/admin.tsx
Labels: ✨ Feat

#168 Feat/#165: 게임 결과 입력하는 칸 추가 및 자동으로 다음 라운드 페이지가 보이도록 추가
  __mocks__/handlers/matchHandlers.ts
  src/components/RoundCheckIn/CallAdminChat.tsx
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/index.tsx
Labels: ✨ Feat

#169 Feat/#167 관리자 페이지 기능 추가
  src/@types/bracket.ts
  src/components/Bracket/BracketContents.tsx
  src/components/Modal/ModifyChannel/ModifyBracket.tsx
  src/components/ModifyChannel/AssignBracket.tsx
  src/components/ModifyChannel/StartMatch.tsx
  src/pages/contents/[channelLink]/admin.tsx
Labels: ✨ Feat

#172 Feat: 관리의 채팅도 제대로된 프로필로 보이도록 추가
  __mocks__/handlers/boardHandlers.ts
  __mocks__/handlers/matchHandlers.ts
  src/components/RoundCheckIn/CallAdminChat.tsx
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/index.tsx
  src/config/index.ts
  src/contexts/CustomContextMenu.tsx
Labels: ✨ Feat

#175 Design: 미리보기 디자인에 공백 추가
  src/components/Content/ContentModify.tsx
Labels: ✒️ Design

#177 Fix/#176: 채널 보드에서 발생하는 문제 해결
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/providers/LastVisitedBoardListsProvider.tsx
Labels: 🛠 Fix

#181 Feat/#170 관리자 알림 확인 기능 및 해당 그룹 바로가기
  __mocks__/constants/matchRoundMock.ts
  src/@types/admin.ts
  src/@types/bracket.ts
  src/@types/icon.ts
  src/components/Icon/index.tsx
  src/components/RoundAlarm/RoundAlarmBody.tsx
  src/components/RoundAlarm/RoundAlarmHeader.tsx
  src/pages/contents/[channelLink]/admin.tsx
Labels: ✨ Feat

#182 Feat/#179 관리자 호출 기능 추가
  src/components/RoundCheckIn/CallAdminChat.tsx
Labels: ✨ Feat

#186 Feat/#178: 유저 기권 및 관리자가 실격처리 할 수 있도록 추가
  __mocks__/handlers/matchHandlers.ts
  src/@types/icon.ts
  src/components/Icon/index.tsx
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
Labels: ✨ Feat

#190 Fix: 새로고침 시 채널 보드 바가 보이지 않는 문제 해결
  src/components/layout.tsx
Labels: 🛠 Fix

#193 Fix/#192: 플레이어 리스트에서 게임 아이디를 한 줄로 표시하도록 수정
  src/components/RoundCheckIn/PlayerLists.tsx
Labels: 🛠 Fix

#189 Fix/#187: 채널 보드 드래그앤 드랍 안되는 문제 해결
  __mocks__/handlers/boardHandlers.ts
  src/@types/board.ts
  src/components/Sidebar/BoardBar/BoardBody.tsx
Labels: 🛠 Fix

#199 Feat/#198: 채널 보드 삭제 기능 추가
  src/components/Content/ContentModify.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: ✨ Feat

#200 Feat/#197 소개 페이지 제작 및 인증상태에 따른 메인 페이지 변경
  public/img/logo/logo-l.png
  public/img/logo/logo-m.png
  public/img/main/main.png
  src/components/Main/NoAuthMain.tsx
  src/components/layout.tsx
  src/components/providers/ProfileProvider.tsx
  src/contexts/ProfileContext.tsx
  src/pages/_app.tsx
  src/pages/auth.tsx
Labels: ✨ Feat

#207 Fix/#206 msw 실행 시점 변경
  src/components/MSWComponent/MSWComponent.tsx
  src/pages/_app.tsx
Labels: 🛠 Fix

#208 Design/#204 BoardBar 디자인 변경
  src/components/DivideLine/DivideLine.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
Labels: ✒️ Design

#209 Fix/#194: 기권처리를 소켓으로 실시간으로 반영되게 수정
  src/components/RoundCheckIn/CheckInPage.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
  src/components/RoundCheckIn/index.tsx
Labels: 🛠 Fix
