Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2023-11, with the labels that each got.

#211 Feat/#205 헤더 문의하기 및 초대코드 복사 기능 추가
  src/@types/icon.ts
  src/components/Header/Header.tsx
  src/components/Icon/index.tsx
Labels: ✨ Feat

#220 Fix: 이미지 업로드 버튼 표시
  src/components/MakeChannel/SelectRule.tsx
Labels: 🛠 Fix

#222 Fix/#215: 채팅 기능 수정
  __mocks__/handlers/matchHandlers.ts
  src/components/RoundCheckIn/CallAdminChat.tsx
  src/components/RoundCheckIn/index.tsx
Labels: 🛠 Fix

#218 Fix/#216 라운드 대진 횟수 설정 에러 해결
  src/@types/channelConfig.ts
  src/components/ModifyChannel/BracketInfoChannel.tsx
  src/components/RoundAlarm/RoundAlarmBody.tsx
Labels: 🛠 Fix

#226 Design/#225 로딩 및 로그인 페이지 디자인 변경
  public/img/main/main.png
  src/components/Main/NoAuthMain.tsx
Labels: ✒️ Design

#227 Feat/#224 LeagueHub Circle 기능 추가
  src/@types/mainPage.ts
  src/components/Header/Header.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/MainChannelCircle.tsx
  src/components/layout.tsx
  src/pages/index.tsx
Labels: ✨ Feat

#228 Design/#223: 채널 생성하는 모달창 디자인 변경
  __test__/components/MakeChannel/SelectGame.test.tsx
  __test__/components/Sidebar/ChannelBar/SelectChannelType.test.tsx
  src/@types/icon.ts
  src/components/Button/Toggle/index.tsx
  src/components/Button/index.tsx
  src/components/Icon/index.tsx
  src/components/MakeChannel/CustomRule.tsx
  src/components/MakeChannel/SelectGame.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/constants/GameImageLink.ts
Labels: ✒️ Design

#230 Feat/#229: 채널 별 메인 홈 화면 추가
  __mocks__/handlers/channelHandlers.ts
  src/components/Card/HomeCard.tsx
  src/components/Content/MainContentModify.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/config/index.ts
  src/pages/contents/[channelLink]/main.tsx
  src/pages/index.tsx
Labels: ✨ Feat

#232 Design: 대회 참여자 모달창 디자인 어두운색 <-> 밝은색 변경
  src/components/Modal/ParticipantLists/index.tsx
Labels: ✒️ Design

#234 Feat/#233: 게임 닉네임 입력 시 게임닉네임#태그번호 로 입력해야하도록 수정
  __test__/components/Modal/JoinLeague/JoinLeague.test.tsx
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
Labels: ✨ Feat, ✒️ Design

#235 Fix: 게임 아이디와 태그번호를 구분해서 입력하도록 수정
  src/components/Modal/JoinLeague/JoinLeague.tsx
Labels: 🛠 Fix

#236 Fix/#221 admin 페이지 변경이 되지않는 문제 수정
  src/components/RoundAlarm/RoundAlarmBody.tsx
  src/pages/contents/[channelLink]/admin.tsx
Labels: 🛠 Fix

#239 Config(config): 변경된 서버 주소로 반영
  src/config/index.ts
Labels: ⚙️ Config

#241 Fix(JoinLeague): 게임 아이디 조회 시 파라미터 형식 변경
  src/components/Modal/JoinLeague/JoinLeague.tsx
Labels: 🛠 Fix

#244 Design/#237 BoardBar 디자인 변경 및 http에서도 클립보드 사용가능하도록 변경
  src/components/Header/Header.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
Labels: ✨ Feat

#246 Design/#245 관리자 페이지 디자인 변경
  src/components/Modal/ModifyChannel/ModifyBracket.tsx
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/ModifyChannel/AssignBracket.tsx
  src/components/ModifyChannel/BasicInfoChannel.tsx
  src/components/ModifyChannel/BracketInfoChannel.tsx
  src/components/ModifyChannel/StartMatch.tsx
  src/components/RoundAlarm/RoundAlarmBody.tsx
  src/components/RoundAlarm/RoundAlarmHeader.tsx
  src/pages/contents/[channelLink]/admin.tsx
Labels: ✨ Feat

#248 Design/#247 마이페이지 및 헤더 드롭다운 디자인 변경
  src/components/Header/Header.tsx
  src/pages/mypage.tsx
Labels: ✒️ Design
