Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2023-08, with the labels that each got.

#58 Config: react-markdown 라이브러리 설치
  package.json
  yarn.lock
Labels: ⚙️ Config

#63 Feat/#62: 게시판 콘텐츠 수정하는 텍스트란 추가
  src/components/Content/ContentModify.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: ✨ Feat

#64 Feat/#48 대회 생성하는 기능 추가
  __mocks__/browser.ts
  __mocks__/handlers/makeGameHandlers.ts
  __mocks__/server.ts
  __test__/components/MakeChannel/SelectGame.test.tsx
  __test__/components/MakeChannel/SelectRule.test.tsx
  __test__/components/Sidebar/ChannelBar/SelectChannelType.test.tsx
  jest.config.js
  package.json
  src/components/Button/Toggle/index.tsx
  src/components/MakeChannel/CustomRule.tsx
  src/components/MakeChannel/SelectGame.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/components/providers/MakeGameProvider.tsx
  src/constants/MakeGame.ts
  src/constants/TFT.ts
  src/contexts/MakeGameContext.tsx
  src/hooks/useMakeGame.tsx
  src/pages/_app.tsx
  src/pages/components/layout.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
  src/pages/make-channel.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ Feat

#68 Feat/#67 boardIdList Context 생성 및 마지막에 접속한 board 확인 기능 추가
  __mocks__/handlers/boardHandlers.ts
  __mocks__/handlers/channelHandlers.ts
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/@types/board.ts
  src/@types/channelCircle.ts
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
  src/components/layout.tsx
  src/components/providers/ChannelProvider.tsx
  src/contexts/ChannelContext.tsx
  src/hooks/useBoardIdLists.tsx
  src/pages/_app.tsx
Labels: ✨ Feat

#71 Fix/#70 오타 및 페이지 강제 이동
  src/components/Content/ContentModify.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: 🛠 Fix

#75 Config/#74 js-cookie 설치 및 클라이언트 ID 변경
  .env
  package.json
  yarn.lock
Labels: ⚙️ Config

#76 Feat/#72 jwt토큰 저장소 변경
  src/apis/authAPI.ts
  src/components/providers/ProfileProvider.tsx
  src/pages/auth.tsx
Labels: ✨ Feat

#79 Feat/#73: 콘텐츠 보는 화면 상단에 채널게시판 제목도 추가
  __mocks__/handlers/boardHandlers.ts
  src/components/Content/ContentModify.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
  src/styles/GlobalStyle.tsx
Labels: ✨ Feat

#81 Fix/#80: 예외 처리 및 모킹 데이터 추가
  __mocks__/handlers/channelHandlers.ts
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/@types/channelCircle.ts
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
  src/components/layout.tsx
Labels: 🛠 Fix

#84 Config: 이미지 도메인 등록
  next.config.js
Labels: ⚙️ Config

#55 Feat/#54: 리그 참여 모달창 구현
  __mocks__/browser.ts
  __mocks__/handlers/statHandlers.ts
  __mocks__/server.ts
  __test__/components/Modal/JoinLeague/JoinLeague.test.tsx
  src/@types/icon.ts
  src/components/Icon/index.tsx
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/hooks/useProfile.ts
Labels: ✨ Feat

#88 Design/#87: 모달 디자인 수정
  src/components/Modal/index.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/styles/GlobalStyle.tsx
Labels: ✒️ Design

#86 Design/#85: 사이드바 가로크기 고정 및 스크롤 바 삭제
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/layout.tsx
  src/styles/GlobalStyle.tsx
Labels: ✒️ Design

#89 Feat/#69 마이페이지 구현
  __mocks__/browser.ts
  __mocks__/handlers/mypageHandlers.ts
  __mocks__/server.ts
  src/@types/icon.ts
  src/@types/mypage.ts
  src/components/Icon/index.tsx
  src/pages/mypage.tsx
  src/utils/checkEmailAddressValidation.ts
Labels: ✨ Feat

#92 Refactor/#90 Context 및 커스텀 훅 이름 변경
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/providers/LastVisitedBoardListsProvider.tsx
  src/contexts/ChannelContext.tsx
  src/contexts/LastVisitedBoardListsContext.tsx
  src/hooks/useBoardIdLists.tsx
  src/hooks/useLastVisitedBoardLists.tsx
  src/pages/_app.tsx
Labels: 🧑‍🔧 Refactor

#93 Refactor/#91: 사이드바 리팩토링
  __mocks__/handlers/boardHandlers.ts
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  src/@types/board.ts
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
  src/components/layout.tsx
Labels: 🧑‍🔧 Refactor

#94 Feat/#82 channels 전역 상태관리
  src/components/layout.tsx
  src/components/providers/ChannelsProvider.tsx
  src/contexts/ChannelsContext.tsx
  src/hooks/useChannels.tsx
  src/pages/_app.tsx
Labels: ✨ Feat

#96 Refactor/#95 대회 개최 페이지 리팩토링
  __mocks__/handlers/channelHandlers.ts
  src/components/Button/Toggle/index.tsx
  src/components/MakeChannel/CustomRule.tsx
  src/components/MakeChannel/SelectGame.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/providers/MakeGameProvider.tsx
  src/constants/MakeGame.ts
  src/constants/TFT.ts
  src/contexts/MakeGameContext.tsx
  src/pages/make-channel.tsx
Labels: 🧑‍🔧 Refactor

#97 Feat/#61: 새 게시글 추가하는 코드 추가
  __mocks__/handlers/channelHandlers.ts
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/constants/MakeBoard.ts
Labels: ✨ Feat

#99 Feat/#98: 대회 참여자정보 학인할 수 있는 모달창 추가
  __mocks__/handlers/profileHandlers.ts
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Modal/ParticipantLists/ParticipantUser.tsx
  src/components/Modal/ParticipantLists/index.tsx
  src/components/Modal/index.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/components/layout.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: ✨ Feat

#102 Config: react-beautiful-dnd 설치
  package.json
  yarn.lock
Labels: ⚙️ Config

#104 Config: @hello-pangea/dnd 설치 및 react-beautiful-dnd 삭제
  package.json
  yarn.lock
Labels: ⚙️ Config

#106 Feat/#65 드래그앤 드랍 구현
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
  src/components/providers/ChannelsProvider.tsx
  src/contexts/ChannelsContext.tsx
Labels: ✨ Feat

#107 Refactor/#105 api 주소 변경 및 서버 주소 변경
  __mocks__/handlers/mypageHandlers.ts
  __mocks__/handlers/profileHandlers.ts
  __mocks__/handlers/statHandlers.ts
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/providers/ProfileProvider.tsx
  src/config/index.ts
  src/pages/auth.tsx
  src/pages/mypage.tsx
Labels: 🧑‍🔧 Refactor

#109 Fix: 최소티어 설정가능하도록 변경
  src/components/MakeChannel/SelectRule.tsx
Labels: 🛠 Fix

#110 Feat/#100: 채널 권한별로 기능 세분화
  __mocks__/handlers/boardHandlers.ts
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/providers/ChannelsProvider.tsx
  src/contexts/ChannelsContext.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: ✨ Feat

#113 Feat/#111: 관리자가 대회 참여자를 강퇴할 수 있도록 추가
  __mocks__/handlers/profileHandlers.ts
  src/components/Modal/ParticipantLists/ParticipantUser.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/providers/ChannelsProvider.tsx
  src/contexts/ChannelsContext.tsx
Labels: ✨ Feat

#115 Feat/#66 대진표 헤더 컴포넌트 만들기
  __mocks__/browser.ts
  __mocks__/handlers/bracketHandlers.ts
  __mocks__/server.ts
  src/@types/bracket.ts
  src/components/Bracket/BracketHeaders.tsx
  src/pages/contents/[channelLink]/bracket.tsx
Labels: ✨ Feat

#117 Feat/#112: 관리자 권한 부여할 수 있는 창 추가
  __mocks__/handlers/profileHandlers.ts
  src/components/Modal/ParticipantLists/ObserverUser.tsx
  src/components/Modal/ParticipantLists/index.tsx
Labels: ✨ Feat

#119 Fix/#118: 채널 게시판에 대한 내용 수정 시 발생하는 문제점 해결
  __mocks__/handlers/boardHandlers.ts
  src/components/Content/ContentModify.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/providers/LastVisitedBoardListsProvider.tsx
  src/contexts/LastVisitedBoardListsContext.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
Labels: ✨ Feat, 🛠 Fix
