Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2023-06, with the labels that each got.

#7 Config: 필요한 라이브러리 설치
  package.json
  yarn.lock
Labels: ⚙️ Config

#9 Feat: 아이콘 컴포넌트 구현
  src/@types/icon.ts
  src/components/Icon/index.tsx
Labels: ✨ Feat

#21 Config: eslint rule 추가
  .eslintrc.json
Labels: ⚙️ Config

#22 Config/#20 emotion 설치
  package.json
  tsconfig.json
  yarn.lock
Labels: ⚙️ Config

#25 Design/#23 전역적으로 설정할 Style 설정
  src/components/layout.tsx
  src/pages/_app.tsx
  src/styles/GlobalStyle.tsx
Labels: ✒️ Design

#28 Test/#27: MSW 설정
  __mocks__/browser.ts
  __mocks__/handlers/testHandlers.ts
  __mocks__/index.ts
  __mocks__/server.ts
  __test__/temporary.test.ts
  jest.config.js
  jest.setup.js
  package.json
  public/mockServiceWorker.js
  src/pages/_app.tsx
  tsconfig.json
Labels: 🔍 Test

#30 Config/#29: React Query 설정
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: ⚙️ Config

#33 Feat/#32: 아이콘 컴포넌트 구현
  jest.config.js
  package.json
  src/@types/icon.ts
  src/components/Icon/index.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ Feat, ⚙️ Config

#31 Feat/#13 ChannelCircle 컴포넌트 구현
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/@types/channelCircle.ts
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
Labels: ✨ Feat

#35 Config/#34: 로그인 전역 Context 생성
  jest.config.js
  src/components/providers/LoginProvider.tsx
  src/contexts/login.ts
  src/hooks/useLogin.ts
  src/pages/_app.tsx
  tsconfig.json
Labels: ⚙️ Config

#39 Feat/#36: 채널 사이드바 구현
  __mocks__/browser.ts
  __mocks__/handlers/channelHandlers.ts
  __mocks__/server.ts
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/layout.tsx
  src/styles/GlobalStyle.tsx
Labels: ✨ Feat

#40 Feat/#38 로그인 구현
  .env
  public/img/auth/kakao_login.png
  src/@types/login.ts
  src/components/Header/Header.tsx
  src/components/layout.tsx
  src/pages/auth.tsx
  src/pages/login.tsx
Labels: ✨ Feat

#44 Feat/#41: 사이드바 (게시판) 구현
  __mocks__/browser.ts
  __mocks__/handlers/boardHandlers.ts
  __mocks__/server.ts
  __test__/components/Sidebar/BoardBar/BoardBar.test.tsx
  src/@types/board.ts
  src/components/Header/Header.tsx
  src/components/Icon/index.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/BoardBar/BoardFooter.tsx
  src/components/Sidebar/BoardBar/BoardHeader.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/layout.tsx
  src/styles/GlobalStyle.tsx
Labels: ✨ Feat

#45 Feat/#43 axios 인스턴스 생성
  jest.config.js
  src/apis/authAPI.ts
  tsconfig.json
Labels: ✨ Feat
