Repository TheUpperPart/leaguehub-frontend, pull requests merged in 2024-01, with the labels that each got.

#273 Config: Update README
  README.md
Labels: 📖 Docs

#277 Config: tanstack-query v5로 변경
  package.json
  src/components/Bracket/BracketContents.tsx
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/ModifyChannel/AssignBracket.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/layout.tsx
  src/contexts/ProfileContext.tsx
  src/pages/_app.tsx
  src/pages/contents/[channelLink]/main.tsx
  src/pages/index.tsx
  yarn.lock
Labels: ⚙️ Config

#278 Refactor/#276: 서버 요청하는 함수를 모듈화
  src/apis/boardContents.ts
  src/apis/boards.ts
  src/apis/bracketContents.ts
  src/apis/brackets.ts
  src/apis/channels.ts
  src/apis/mainContents.ts
  src/apis/match.ts
  src/apis/mypage.ts
  src/apis/roundInfo.ts
  src/apis/utils.ts
  src/components/Bracket/BracketContents.tsx
  src/components/Header/Header.tsx
  src/components/MakeChannel/SelectRule.tsx
  src/components/Modal/JoinLeague/JoinLeague.tsx
  src/components/Modal/ModifyChannel/ModifyChannel.tsx
  src/components/Modal/ParticipantLists/ObserverUser.tsx
  src/components/Modal/ParticipantLists/ParticipantUser.tsx
  src/components/Modal/ParticipantLists/RequestUser.tsx
  src/components/ModifyChannel/AssignBracket.tsx
  src/components/ModifyChannel/BasicInfoChannel.tsx
  src/components/ModifyChannel/BracketInfoChannel.tsx
  src/components/ModifyChannel/StartMatch.tsx
  src/components/RoundAlarm/RoundAlarmBody.tsx
  src/components/RoundCheckIn/PlayerLists.tsx
  src/components/RoundCheckIn/index.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/BoardBody.tsx
  src/components/Sidebar/ChannelBar/SelectChannelType.tsx
  src/components/providers/ChannelsProvider.tsx
  src/components/providers/ProfileProvider.tsx
  src/pages/contents/[channelLink]/[boardId].tsx
  src/pages/contents/[channelLink]/admin.tsx
  src/pages/contents/[channelLink]/main.tsx
  src/pages/index.tsx
  src/pages/mypage.tsx
Labels: 🧑‍🔧 Refactor

#279 Feat/#274 SSR에서 토큰 탑재 자동화 및 마이페이지 리팩토링
  src/apis/mypage.ts
  src/constants/queryManagement.ts
  src/hooks/mutation/useSendEmailMutation.ts
  src/hooks/query/useMyPageQuery.ts
  src/hooks/useInput.ts
  src/pages/mypage.tsx
  src/utils/withAuthentication.tsx
Labels: ✨ Feat

#281 Design/#280 theme 시스템 구축 및 관리자 페이지 디자인 변경
  __test__/components/Sidebar/ChannelCircle/ChannelCircle.test.tsx
  src/@types/emotion.d.ts
  src/apis/match.ts
  src/apis/roundInfo.ts
  src/components/Header/Header.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/Modal/index.tsx
  src/components/RoundAlarm/AlarmButton.tsx
  src/components/RoundAlarm/AlarmButtonContent.tsx
  src/components/RoundAlarm/RoundAlarm.tsx
  src/components/RoundAlarm/RoundAlarmBody.tsx
  src/components/RoundAlarm/RoundAlarmHeader.tsx
  src/components/Sidebar/BoardBar/BoardBar.tsx
  src/components/Sidebar/BoardBar/ChannelBarContent/BoardBody.tsx
  src/components/Sidebar/BoardBar/ChannelBarContent/BoardFooter.tsx
  src/components/Sidebar/BoardBar/ChannelBarContent/BoardHeader.tsx
  src/components/Sidebar/BoardBar/ChannelBoardBar.tsx
  src/components/Sidebar/BoardBar/MainBar.tsx
  src/components/Sidebar/ChannelBar/ChannelBar.tsx
  src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
  src/components/Sidebar/ChannelCircle/MainChannelCircle.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/contents/[channelLink]/admin.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/ThemeStyle.tsx
Labels: ⚙️ Config, 🧑‍🔧 Refactor, ✒️ Design
